[tool.poetry]
name = "kbgpt"
version = "0.1.0"
description = ""
authors = ["Vince <vince@surfin.sg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.09"
langchain = "^0.0.129"
openai = "^0.27.2"
bs4 = "^0.0.1"
lxml = "^4.9.2"
tiktoken = "^0.3.3"

[tool.poetry.dev-dependencies]
flake8 = "*"
pylint = "*"


[tool.poetry.group.dev.dependencies]
pyramid = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
