PROFILE: FAT

DEFAULT:
  DB_URL: mysql+pymysql://user:password@localhost:3306/db
  GENERATIVE_MODEL: "gpt-3.5-turbo"
# ----- SANIC SERVER PORT ----
  SANIC:
    APP_NAME: kbgpt
    PORT: 8081
    IP: "0.0.0.0"
    DEBUG: True
    WORKERS: 1
  COMMENT:
    GENERATIVE_MODEL: "gpt-3.5-turbo"
  SENTIMENT:
    ANALYSIS_MODEL: "gpt-3.5-turbo"
  REPORT:
    REDIS_URL: "redis://18.139.228.114:6380/0"
    BACKEND_ADMIN_URL: "http://test1.backend-admin.testbs.surfin.sg/v1/internal/aigc/create"
  QA:
    EMBEDDINGS_MODEL: "text-embedding-ada-002"
    GENERATIVE_MODEL: "gpt-3.5-turbo"
    CUSTOMER_SERVICE_TEMPERATURE: 0.3
    AGENT_CLS: builtin
    REQUEST_TIMEOUT: 60
    REQUEST_RETRY: 2
    keep_msg_history: True
    words_limit: 50
# ----- DOCUMENT EMBEDDING CONFIG -----
  EMBEDDING:
    EMBEDDING_DIMENSIONS: 1536
    TEXT_EMBEDDING_CHUNK_SIZE: 1000
    TEXT_EMBEDDING_CHUNK_OVERLAP: 200
    EMBEDDINGS_FUNCTION: openai
# ----- VECTOR STORE CONFIG -----
  VECTOR_STORE:
    VECTOR_STORE_CLASS: redis
    VECTOR_RETRIVAL_K: 3
    REDIS_URL: "redis://localhost:6379"
    PINECONE_ENV: us-west4-gcp
    CHROMA_PERSIST_DIR: .chroma/data
  CACHE:
    USE_REDIS_CACHE: True
    REDIS_CACHE_SIMILARITY_THRESHOLD: 0.05
    CUSTOMER_SERVICE_CACHE_INDEX: cache-bullsmart-customer-services
    FRESH_BATCH_SIZE: 10
    COOL_DOWN_SECONDS: 100
  INDEXING:
    FLUSH_BEFORE_WRITE: True
    CUSTOMER_SERVICE_INDEX: bullsmart-customer-services

FAT:
  SANIC:
    DEBUG: True
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"

PRE:
  SANIC:
    DEBUG: True
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"

PROD:
  SANIC:
    DEBUG: False
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"