PROFILE: FAT

DEFAULT:
  DB_URL: mysql+pymysql://user:password@localhost:3306/db
  BASEURL: http://localhost:8081
  GENERATIVE_MODEL: "gpt-3.5-turbo"
  OPENAI:
    PROXIED: True
    PROXY_URL: http://18.139.228.114:81
    API_BASE_URL: http://api.openai.com/v1
  # ----- SANIC SERVER PORT ----
  SANIC:
    APP_NAME: kbgpt
    PORT: 8081
    IP: "0.0.0.0"
    DEBUG: True
    WORKERS: 1
    RESPONSE_TIMEOUT: 600
  COMMENT:
    GENERATIVE_MODEL: "gpt-3.5-turbo"
  SENTIMENT:
    ANALYSIS_MODEL: "gpt-3.5-turbo"
  REPORT:
    BACKEND_ADMIN_URL: "http://test1.backend-admin.testbs.surfin.sg/v1/internal/aigc/create"
    TRENDING_URL: "http://mb-api-gateway.testbs.surfin.sg"
    OPENAI_MODEL: "gpt-3.5-turbo-16k"
  QA:
    EMBEDDINGS_MODEL: "text-embedding-ada-002"
    GENERATIVE_MODEL: "gpt-3.5-turbo-16k"
    CUSTOMER_SERVICE_TEMPERATURE: 0
    AGENT_CLS: builtin
    REQUEST_TIMEOUT: 60
    REQUEST_RETRY: 2
    keep_msg_history: True
    words_limit: 25
    redis_index: bullsmart-customer-services
    recomm:
      gpt3_5_model: "gpt-3.5-turbo-16k"
      gpt4_model: "gpt-4"
  PRODUCT_CATALOG:
    vector_store_class: redis_no_lock
    redis_index_name: bullsmart-product-catalog
  # ----- DOCUMENT EMBEDDING CONFIG -----
  EMBEDDING:
    EMBEDDING_DIMENSIONS: 1536
    TEXT_EMBEDDING_CHUNK_SIZE: 1000
    TEXT_EMBEDDING_CHUNK_OVERLAP: 200
    EMBEDDINGS_FUNCTION: openai
  # ----- VECTOR STORE CONFIG -----
  VECTOR_STORE:
    VECTOR_STORE_CLASS: redis_cache_lock
    VECTOR_RETRIVAL_K: 3
    REDIS_URL: "redis://localhost:6379"
    PINECONE_ENV: us-west4-gcp
    CHROMA_PERSIST_DIR: .chroma/data
  CACHE:
    USE_REDIS_CACHE: True
    REDIS_CACHE_SIMILARITY_THRESHOLD: 0.05
    CUSTOMER_SERVICE_CACHE_INDEX: cache-bullsmart-customer-services
    FRESH_BATCH_SIZE: 10
    COOL_DOWN_SECONDS: 100

FAT:
  BASEURL: http://py-kbgpt.testbs.surfin.sg
  OPENAI:
    PROXIED: False
  SANIC:
    DEBUG: True
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"

PRE:
  BASEURL: http://py-kbgpt-pre.bullsmart.in
  OPENAI:
    PROXIED: False
  SANIC:
    DEBUG: True
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"
  REPORT:
    BACKEND_ADMIN_URL: "http://backend-admin-pre.bullsmart.in/v1/internal/aigc/create"
    TRENDING_URL: "https://mb-api-gateway-pre.bullsmart.in"

PROD:
  BASEURL: http://py-kbgpt.bullsmart.in
  OPENAI:
    PROXIED: False
  SANIC:
    DEBUG: False
  VECTOR_STORE:
    REDIS_URL: "redis://redis-stack.ops:6379"
  REPORT:
    BACKEND_ADMIN_URL: "https://backend-admin.bullsmart.in/v1/internal/aigc/create"
    TRENDING_URL: "https://mb-api-gateway.bullsmart.in"
